### ISSUE TITLE
Ember.js 2.x+ - double render deprecations

### ISSUE THREAD

**Issue by spovich** [jasonkriss/ember-float-label#2]
When we added  `ember-float-label` to our ember.js 2.1.0 app we noticed several deprecations.  It looks like 2 double render deprecations for each rendered input field using `ember-float-label`.

```
DEPRECATION: You modified (-join-classes "ember-view" "float-label" undefined (-normalize-class "hasValue" hasValue activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16671:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16581:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16671:7)
        at invoke (http://localhost:4200/assets/vendor.js:16687:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16640:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26649:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53144:26)
        at http://localhost:4200/assets/vendor.js:23878:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:32275:11)
```

```
DEPRECATION: You modified label twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16671:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16581:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16671:7)
        at invoke (http://localhost:4200/assets/vendor.js:16687:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16640:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26649:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53144:26)
        at http://localhost:4200/assets/vendor.js:23878:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:32275:11)
```

**Comment by jasonkriss** [comment]
@spovich Thanks for pointing that out. This is likely happening as a result of how we [register inputs their corresponding float label](https://github.com/jasonkriss/ember-float-label/blob/master/addon/mixins/registrable.js#L5). I'm probably not gonna have a chance to fix this in the immediate future so if you are feeling up to it, a PR would be greatly appreciated. Otherwise, I'll try to get to it as soon as I can.

**Comment by spovich** [comment]
@jasonkriss ok, yea, lots of changes with life-cycle hooks.  I'm not really sure how this might be fixed.  If I have some time (not in the near-term), I'll let you know if I start looking into this.

**Comment by jasonkriss** [comment]
sounds good. Thanks @spovich!
